export enum Theme {
  Dark = 'dark',
  Light = 'light',
}

export enum ThemeType {
  bg = 1,
  word = 2,
  bgI = 3,
}

export enum Language {
  CN = 'cn',
  EN = 'en',
}

export enum AllIn {
  WalletValue = 1000,
  DepositValue = 1000,
  BnbValue = '10000000000000000000000',
  DepositValue2 = 10000,
  LockDay = 180,
  LockDay2 = 10,
}

export const element = [
  'Hydrogen',
  'Helium',
  'Lithium',
  'Beryllium',
  'Boron',
  'Carbon',
  'Nitrogen',
  'Oxygen',
  'Fluorine',
  'Neon',
  'Sodium',
  'Magnesium',
  'Aluminium',
  'Silicon',
  'Phosphorus',
  'Sulphur',
  'Chlorine',
  'Argon',
  'Potassium',
  'Calcium',
  'Scandium',
  'Titanium',
  'Vanadium',
  'Chromium',
  'Manganese',
  'Iron',
  'Cobalt',
  'Nickel',
  'Copper',
  'Zinc',
  'Gallium',
  'Germanium',
  'Arsenic',
  'Selenium',
  'Bromine',
  'Krypton',
  'Rubidium',
  'Strontium',
  'Yttrium',
  'Zirconium',
  'Niobium',
  'Molybdenum',
  'Technetium',
  'Ruthenium',
  'Rhodium',
  'Palladium',
  'Silver',
  'Cadmium',
  'Indium',
  'Tin',
  'Antimony',
  'Tellurium',
  'Iodine',
  'Xenon',
  'Cesium',
  'Barium',
  'Lanthanum',
  'Cerium',
  'Praseodymium',
  'Neodymium',
  'Promethium',
  'Samarium',
  'Europium',
  'Gadolinium',
  'Terbium',
  'Dysprosium',
  'Holmium',
  'Erbium',
  'Thulium',
  'Ytterbium',
  'Lutetium',
  'Hafnium',
  'Tantalum',
  'Tungsten',
  'Rhenium',
  'Osmium',
  'Iridium',
  'Platinum',
  'Gold',
  'Mercury',
  'Thallium',
  'Lead',
  'Bismuth',
  'Polonium',
  'Astatine',
  'Radon',
  'Francium',
  'Radium',
  'Actinium',
  'Thorium',
  'Protactinium',
  'Uranium',
  'Neptunium',
  'Plutonium',
  'Americium',
  'Curium',
  'Berkelium',
  'Californium',
]

export const country = [
  'AFGHANISTAN',
  'ALBANIA',
  'ALGERIA',
  'AMERICAN SAMOA',
  'ANDORRA',
  'ANGOLA',
  'ANGUILLA',
  'ANTARCTICA',
  'ANTIGUA AND BARBUDA',
  'ARGENTINA',
  'ARMENIA',
  'ARUBA',
  'AUSTRALIA',
  'AUSTRIA',
  'AZERBAIJAN',
  'BAHAMAS',
  'BAHRAIN',
  'BANGLADESH',
  'BARBADOS',
  'BELARUS',
  'BELGIUM',
  'BELIZE',
  'BENIN',
  'BERMUDA',
  'BHUTAN',
  'BOLIVIA',
  'BOSNIA AND HERZEGOVINA',
  'BOTSWANA',
  'BOUVET ISLAND',
  'BRAZIL',
  'BRITISH INDIAN OCEAN TER-RITORY',
  'BRUNEI DARUSSALAM',
  'BULGARIA',
  'BURKINA FASO',
  'BURUNDI',
  'CAMBODIA',
  'CAMEROON',
  'CANADA',
  'CAPE VERDE',
  'CAYMAN ISLANDS',
  'CENTRAL AFRICA',
  'CHAD',
  'CHILE',
  'CHINA',
  'HONG KONG',
  'MACAU',
  'TAIWAN, PROVINCE OF CHINA',
  'CHRISTMAS ISLAND',
  'COCOS（KEELING） ISLANDS',
  'COLOMBIA',
  'COMOROS',
  'CONGO',
  'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
  'COOK ISLANDS',
  'COSTA RICA',
  'COTE DIVOIRE',
  'CROATIA',
  'CUBA',
  'CYPRUS',
  'CZECH REPOUBLIC',
  'DENMARK',
  'DJIBOUTI',
  'DOMINICA',
  'DOMINICAN REPUBLIC',
  'EAST TIMOR',
  'ECUADOR',
  'EGYPT',
  'EL SALVADOR',
  'EQUATORIAL GUINEA',
  'ERITREA',
  'ESTONIA',
  'ETHIOPIA',
  'FALKLAND ISLANDS（MALVINAS）',
  'FAROE ISLANDS',
  'FIJI',
  'FINLAND',
  'FRANCE',
  'FRENCH GUIANA',
  'FRENCH POLYNESIA',
  'FRENCH SOUTHERN TERRITO-RIES',
  'GABON',
  'GAMBIA',
  'GEORGIA',
  'GERMANY',
  'GHANA',
  'GIBRALTAR',
  'GREECE',
  'GREENLAND',
  'GRENADA',
  'GUADELOUPE',
  'GUAM',
  'GUATEMALA',
  'GUINEA',
  'GUINE-BISSAU',
  'GUYANA',
  'HAITI',
  'HEARD ISLANDS AND MC DONALD ISLANDS',
  'HONDURAS',
  'HUNGARY',
  'ICELAND',
  'INDIA',
  'INDONESIA',
  'IRAN',
  'IRAQ',
  'IRELAND',
  'ISRAEL',
  'ITALY',
  'JAMAICA',
  'JAPAN',
  'JORDAN',
  'KAZAKHSTAN',
  'KENYA',
  'KIRIBATI',
  "KOREA,DEMOCRATIC PEOPLE'S REPUBLIC OF",
  'KOREA,REPUBLIC OF',
  'KUWAIT',
  'KYRGYZSTAN',
  'LAOS',
  'LATVIA',
  'LEBANON',
  'LESOTHO',
  'LIBERIA',
  'LIBYA',
  'LIECHTENSTEIN',
  'LITHUANIA',
  'LUXEMBOURG',
  'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
  'MADAGASCAR',
  'MALAWI',
  'MALAYSIA',
  'MALDIVES',
  'MALI',
  'MALTA',
  'MARSHALL ISLANDS',
  'MARTINIQUE',
  'MAURITANIA',
  'MAURITIUS',
  'MAYOTTE',
  'MEXICO',
  'MICRONESIA, FEDERATED STATES OF',
  'MOLDOVA',
  'MONACO',
  'MONGOLIA',
  'MONTSERRAT',
  'MOROCCO',
  'MOZAMBIQUE',
  'MYANMAR',
  'NAMIBIA',
  'NAURU',
  'NEPAL',
  'NETHERLANDS',
  'NETHERLANDS ANTILLES',
  'NEW CALEDONIA',
  'NEW ZEALAND',
  'NICARAGUA',
  'NIGER',
  'NIGERIA',
  'NIUE',
  'NORFOLK ISLAND',
  'NORTHERN MARIANAS',
  'NORWAY',
  'OMAN',
  'PAKISTAN',
  'PALAU',
  'PALESTINE',
  'PANAMA',
  'PAPUA NEW GUINEA',
  'PARAGUAY',
  'PERU',
  'PHILIPPINES',
  'PITCAIRN ISLANDS GROUP',
  'POLAND',
  'PORTUGAL',
  'PUERTO RICO',
  'QATAR',
  'REUNION',
  'ROMANIA',
  'RUSSIAN FEDERATION',
  'RWANDA',
  'SAINT HELENA',
  'SAINT KITTS AND NEVIS',
  'SAINT LUCIA',
  'SAINT PIERRE AND MIQUELON',
  'SAINT VINCENT AND THE GRENADINES',
  'SAMOA',
  'SAN MARION',
  'SAO TOME AND PRINCIPE',
  'SAUDI ARABIA',
  'SENEGAL',
  'SEYCHELLS',
  'SIERRA LEONE',
  'SINGAPORE',
  'SLOVAKIA',
  'SLOVENIA',
  'SOLOMON ISLANDS',
  'SOMALIA',
  'SOUTH AFRICA',
  'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS',
  'SPAIN',
  'SRI LANKA',
  'SUDAN',
  'SURINAME',
  'SVALBARD AND JAN MAYEN ISLANDS',
  'SWAZILAND',
  'SWEDEN',
  'SWITZERLAND',
  'SYRIA',
  'TAJIKISTAN',
  'TANZANIA',
  'THAILAND',
  'TOGO',
  'TOKELAU',
  'TONGA',
  'TRINIDAD AND TOBAGO',
  'TUNISIA',
  'TURKEY',
  'TURKMENISTAN',
  'TURKS AND CAICOS ISLANDS',
  'TUVALU',
  'UGANDA',
  'UKRAINE',
  'UNITED ARAB EMIRATES',
  'UNITED KINGDOM',
  'UNITED STATES',
  'UNITED STATES MINOR OUTLYING ISLANDS',
  'URUGUAY',
  'UZBEKISTAN',
  'VANUATU',
  'VATICAN',
  'VENEZUELA',
  'VIET NAM',
  'VIRGIN ISLANDS, BRITISH',
  'VIRGIN ISLANDS,U.S.',
  'WALLIS AND FUTUNA',
  'WESTERN SAHARA',
  'YEMEN',
  'YUGOSLAVIA',
  'ZAMBIA',
  'ZIMBABWE',
]

export const publicChain = ['Ethereum', 'BSC', 'Solana', 'Polygon', 'Avalanche']
